# Generated by Django 2.0.3 on 2018-04-06 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(unique=True)),
                ('category', models.CharField(max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('slug', models.CharField(max_length=60, unique=True)),
                ('likes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.CharField(max_length=60, primary_key=True, serialize=False, unique=True)),
                ('post_url', models.CharField(max_length=80)),
                ('post_text', models.TextField(null=True)),
                ('share_count', models.IntegerField(null=True)),
                ('like_count', models.IntegerField(null=True)),
                ('love_count', models.IntegerField(null=True)),
                ('wow_count', models.IntegerField(null=True)),
                ('haha_count', models.IntegerField(null=True)),
                ('sad_count', models.IntegerField(null=True)),
                ('angry_count', models.IntegerField(null=True)),
                ('comment_count', models.IntegerField(null=True)),
                ('posted_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook_news_scraper.Article')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facebook_news_scraper.Page')),
            ],
        ),
    ]
