# Generated by Django 2.0.3 on 2018-04-06 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_news_scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pub_category',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='pub_headline',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='pub_lede',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='resolved_url',
            field=models.TextField(null=True),
        ),
    ]
