# Generated by Django 2.0.3 on 2018-04-06 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_news_scraper', '0002_auto_20180406_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='loaded',
            field=models.BooleanField(default=False),
        ),
    ]
