# Generated by Django 2.0.3 on 2018-04-06 03:42

from django.db import migrations, models
import django.db.models.deletion

def set_publications(apps, schema_editor):
    posts = apps.get_model('facebook_news_scraper', 'Post').objects.all()
    total = len(posts)
    i = 0
    print()
    print()
    for post in posts.iterator():
        post.article.pub = post.page
        post.article.save()
        i += 1
        print('Migrated post %i/%i' % (i, total), end='\r')

class Migration(migrations.Migration):

    dependencies = [
        ('facebook_news_scraper', '0003_article_loaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facebook_news_scraper.Page'),
            preserve_default=False,
        ),
        migrations.RunPython(set_publications),
        migrations.AlterField(
            model_name='article',
            name='pub',
            field=models.ForeignKey(null=False, on_delete=django.db.models.deletion.CASCADE, to='facebook_news_scraper.Page'),
        ),
    ]
            
