# Generated by Django 2.0.3 on 2018-04-06 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_news_scraper', '0004_article_pub'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pub_keywords',
            field=models.TextField(null=True),
        ),
    ]
