# Generated by Django 2.0.3 on 2018-04-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_news_scraper', '0005_article_pub_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='scraped',
            field=models.BooleanField(default=False),
        ),
    ]
