# Generated by Django 2.0.3 on 2018-04-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_news_scraper', '0006_article_scraped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_category',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
