# Generated by Django 2.0.3 on 2018-06-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_news_scraper', '0007_auto_20180409_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='total_shares',
            field=models.IntegerField(default=0),
        ),
    ]
