# Generated by Django 2.0.3 on 2018-06-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_news_scraper', '0008_article_total_shares'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='total_comments',
            field=models.IntegerField(default=0),
        ),
    ]
