# Generated by Django 2.0.3 on 2018-07-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_news_scraper', '0009_article_total_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='total_reactions',
            field=models.IntegerField(default=0),
        ),
    ]
