version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - PGDATA=/data/postgres/data
    volumes:
      - ./../psql-data:/data/postgres
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - ./logs:/logs
    ports:
      - "8000:8000"
    depends_on:
      - db