category_map = {
  '2016 presidential race': 'politics',
  '2018 elections': 'politics',
  'afghanistan': 'world',
  'africa': 'world',
  'america': 'world',
  'americas': 'world',
  'art & design': 'lifestyle',
  'art and design': 'lifestyle',
  'arts': 'lifestyle',
  'asia pacific': 'world',
  'asia': 'world',
  'australia news': 'world',
  'australia': 'world',
  'baseball': 'sports',
  'book review': 'lifestyle',
  'book reviews': 'lifestyle',
  'books': 'lifestyle',
  'business day': 'business',
  'california living': 'lifestyle',
  'canada': 'world',
  'celebrity': 'lifestyle',
  'china': 'world',
  'climate': 'science',
  'college basketball': 'sports',
  'comedy': 'lifestyle',
  'companies': 'business',
  'congress': 'politics',
  'crime': 'national',
  'culture & arts': 'lifestyle',
  'culture': 'lifestyle',
  'dance': 'lifestyle',
  'dealbook': 'business',
  'divorce': 'lifestyle',
  'economy': 'national',
  'education': 'national',
  'energy & environment': 'science',
  'energy and environment': 'science',
  'energy': 'science',
  'entertainment': 'lifestyle',
  'environment': 'science',
  'essential politics': 'politics',
  'essential washington': 'politics',
  'europe': 'world',
  'family': 'lifestyle',
  'fashion & style': 'lifestyle',
  'fashion': 'lifestyle',
  'film': 'lifestyle',
  'finance': 'business',
  'fine art': 'lifestyle',
  'fitness + well-being': 'lifestyle',
  'florida school shooting': 'national',
  'food & drink': 'lifestyle',
  'food': 'lifestyle',
  'football': 'sports',
  'games': 'lifestyle',
  'global development': 'world',
  'global': 'world',
  'golf': 'sports',
  'health & wellness': 'lifestyle',
  'health': 'lifestyle',
  'healthcare professionals network': 'science',
  'home & garden': 'lifestyle',
  'home & living': 'lifestyle',
  'immigration': 'national',
  'india': 'world',
  'innovations': 'business',
  'inspired life': 'lifestyle',
  'international': 'world',
  'investing': 'business',
  'latin america': 'world',
  'lens': 'lifestyle',
  'life and style': 'lifestyle',
  'life': 'lifestyle',
  'living': 'lifestyle',
  'markets': 'business',
  'media': 'business',
  'mental health': 'lifestyle',
  'middle east': 'world',
  'middleeast': 'world',
  'money': 'business',
  'movie reviews': 'lifestyle',
  'movies': 'lifestyle',
  'music news': 'lifestyle',
  'music': 'lifestyle',
  'nation': 'national',
  'national security': 'national',
  'nba': 'sports',
  'nfl': 'sports',
  'ny / region': 'local',
  'olympics': 'sports',
  'opinions': 'opinion',
  'parenting': 'lifestyle',
  'personal tech': 'lifestyle',
  'pets': 'lifestyle',
  'poetry': 'lifestyle',
  'pop culture': 'lifestyle',
  'pro basketball': 'sports',
  'pro football': 'sports',
  'race': 'national',
  'real estate': 'lifestyle',
  'recipes': 'lifestyle',
  'religion': 'lifestyle',
  'retirement': 'lifestyle',
  'russia investigation': 'politics',
  'saudi arabia': 'world',
  'science & environment': 'science',
  'shopping': 'lifestyle',
  'smallbusiness': 'business',
  'smarter living': 'lifestyle',
  'soccer': 'sports',
  'space & cosmos': 'science',
  'sport': 'sports',
  'stage': 'lifestyle',
  'style & beauty': 'lifestyle',
  'style': 'lifestyle',
  'tech': 'business',
  'technology': 'business',
  'television & radio': 'lifestyle',
  'television': 'lifestyle',
  'tennis': 'sports',
  'theater': 'lifestyle',
  'travel': 'lifestyle',
  'tv reviews': 'lifestyle',
  'tvandmovies': 'lifestyle',
  'u.s. news': 'national',
  'u.s.': 'national',
  'us & canada': 'national',
  'us news': 'national',
  'us': 'national',
  'usnews': 'national',
  'video and tv': 'national',
  'watching': 'lifestyle',
  'weather': 'national',
  'weddings': 'lifestyle',
  'well': 'lifestyle',
  'wellness': 'lifestyle',
  'winter olympics': 'sports',
  'world news': 'world',
  'your money': 'lifestyle',
}